"""add_newspaper_system

Revision ID: 012c47ddf8f1
Revises: 124cfa442472
Create Date: 2025-11-09 17:52:41.291870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012c47ddf8f1'
down_revision = '124cfa442472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newspaper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newspaper_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newspaper_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_newspaper_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_newspaper_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_newspaper_owner_id'), ['owner_id'], unique=False)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('newspaper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_newspaper_id'), ['newspaper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)

    op.create_table('newspaper_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newspaper_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspaper.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newspaper_id', 'subscriber_id', name='unique_newspaper_subscription')
    )
    with op.batch_alter_table('newspaper_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newspaper_subscription_newspaper_id'), ['newspaper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newspaper_subscription_subscriber_id'), ['subscriber_id'], unique=False)

    op.create_table('article_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['article_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_comment_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_comment_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_comment_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_comment_parent_comment_id'), ['parent_comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_comment_user_id'), ['user_id'], unique=False)

    op.create_table('article_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'user_id', name='unique_article_vote')
    )
    with op.batch_alter_table('article_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_vote_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_vote_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_article_vote_article_id'))

    op.drop_table('article_vote')
    with op.batch_alter_table('article_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_article_comment_parent_comment_id'))
        batch_op.drop_index(batch_op.f('ix_article_comment_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_article_comment_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_article_comment_article_id'))

    op.drop_table('article_comment')
    with op.batch_alter_table('newspaper_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newspaper_subscription_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_newspaper_subscription_newspaper_id'))

    op.drop_table('newspaper_subscription')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_newspaper_id'))
        batch_op.drop_index(batch_op.f('ix_article_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_article_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_article_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_author_id'))

    op.drop_table('article')
    with op.batch_alter_table('newspaper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newspaper_owner_id'))
        batch_op.drop_index(batch_op.f('ix_newspaper_name'))
        batch_op.drop_index(batch_op.f('ix_newspaper_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_newspaper_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_newspaper_country_id'))

    op.drop_table('newspaper')
    # ### end Alembic commands ###
