"""Add username, description, avatar fields to User for profile

Revision ID: 01363b302391
Revises: 504b2064a3fb
Create Date: 2025-04-28 23:28:38.074068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01363b302391'
down_revision = '504b2064a3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.Boolean(), nullable=True, default=False)) # Add default
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        # Make avatar default to False explicitly in existing rows if needed
        # op.execute("UPDATE user SET avatar = 0 WHERE avatar IS NULL") # If column might have NULLs

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('avatar')
        batch_op.drop_column('description')
        batch_op.drop_column('username')

    # ### end Alembic commands ###