"""Add military skills and last_trained to User

Revision ID: 016e7687122e
Revises: a0fc4f8a8851
Create Date: 2025-04-29 17:57:25.397495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e7687122e'
down_revision = 'a0fc4f8a8851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add columns with appropriate defaults and non-nullable constraints
        batch_op.add_column(sa.Column('skill_infantry', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('skill_armoured', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('skill_aviation', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('last_trained', sa.DateTime(), nullable=True))

    # Ensure defaults are applied to existing rows if server_default didn't work
    op.execute("UPDATE user SET skill_infantry = 0.0 WHERE skill_infantry IS NULL")
    op.execute("UPDATE user SET skill_armoured = 0.0 WHERE skill_armoured IS NULL")
    op.execute("UPDATE user SET skill_aviation = 0.0 WHERE skill_aviation IS NULL")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_trained')
        batch_op.drop_column('skill_aviation')
        batch_op.drop_column('skill_armoured')
        batch_op.drop_column('skill_infantry')

    # ### end Alembic commands ###