"""Add GoldMarket model

Revision ID: 0204e2462318
Revises: 51bb8e6f5a6d
Create Date: 2025-05-08 15:29:19.087907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0204e2462318'
down_revision = '51bb8e6f5a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
