"""Change market progress and inventory quantity to Integer

Revision ID: 023c71028da1
Revises: b93bc293851c
Create Date: 2025-05-04 20:52:09.897506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '023c71028da1'
down_revision = 'b93bc293851c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Modify country_market_item ---
    # MySQL needs explicit MODIFY COLUMN. Other DBs might use ALTER COLUMN.
    # Need to handle potential data loss if floats exist. Common strategy is to TRUNCATE.
    op.execute("ALTER TABLE country_market_item MODIFY COLUMN progress_within_level INTEGER NOT NULL DEFAULT 0")
    # Note: If using SQLite, batch mode is needed:
    # with op.batch_alter_table('country_market_item', schema=None) as batch_op:
    #     batch_op.alter_column('progress_within_level',
    #            existing_type=mysql.FLOAT(), # Or sa.Float() if type object needed
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'0.0'")) # Adjust existing default if needed

    # --- Modify inventory_item ---
    # Similar modification for quantity
    op.execute("ALTER TABLE inventory_item MODIFY COLUMN quantity INTEGER NOT NULL DEFAULT 0")
    # Note: If using SQLite, batch mode is needed:
    # with op.batch_alter_table('inventory_item', schema=None) as batch_op:
    #     batch_op.alter_column('quantity',
    #            existing_type=mysql.FLOAT(), # Or sa.Float()
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'0.0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Modify inventory_item back to Float ---
    op.execute("ALTER TABLE inventory_item MODIFY COLUMN quantity FLOAT NOT NULL DEFAULT 0.0")
    # Note: If using SQLite, batch mode is needed:
    # with op.batch_alter_table('inventory_item', schema=None) as batch_op:
    #     batch_op.alter_column('quantity',
    #            existing_type=sa.Integer(),
    #            type_=mysql.FLOAT(), # Or sa.Float()
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'0'")) # Adjust existing default

    # --- Modify country_market_item back to Float ---
    op.execute("ALTER TABLE country_market_item MODIFY COLUMN progress_within_level FLOAT NOT NULL DEFAULT 0.0")
    # Note: If using SQLite, batch mode is needed:
    # with op.batch_alter_table('country_market_item', schema=None) as batch_op:
    #     batch_op.alter_column('progress_within_level',
    #            existing_type=sa.Integer(),
    #            type_=mysql.FLOAT(), # Or sa.Float()
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'0'")) # Adjust existing default

    # ### end Alembic commands ###