"""Change market logic to stock level

Revision ID: 038e07badb73
Revises: 254ae07de84f
Create Date: 2025-05-04 12:13:26.521231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '038e07badb73'
down_revision = '254ae07de84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_market_item', schema=None) as batch_op:
        # Add new columns with defaults
        batch_op.add_column(sa.Column('initial_price', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.0')) # Add default
        batch_op.add_column(sa.Column('current_stock_level', sa.Integer(), nullable=False, server_default='0')) # Add default

        # Drop old columns
        batch_op.drop_column('current_price')
        batch_op.drop_column('volume_since_last_change')

    # Apply default values to existing rows if server_default didn't catch them
    op.execute("UPDATE country_market_item SET initial_price = 0.0 WHERE initial_price IS NULL")
    op.execute("UPDATE country_market_item SET current_stock_level = 0 WHERE current_stock_level IS NULL")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_market_item', schema=None) as batch_op:
        # Add back old columns (might need defaults if they were non-nullable)
        batch_op.add_column(sa.Column('volume_since_last_change', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('current_price', mysql.DECIMAL(precision=10, scale=4), nullable=False, server_default='0.0'))

        # Drop new columns
        batch_op.drop_column('current_stock_level')
        batch_op.drop_column('initial_price')

    # Apply defaults if needed
    op.execute("UPDATE country_market_item SET volume_since_last_change = 0 WHERE volume_since_last_change IS NULL")
    op.execute("UPDATE country_market_item SET current_price = 0.0 WHERE current_price IS NULL")


    # ### end Alembic commands ###