"""add_friendship_table

Revision ID: 07d9131fee5d
Revises: 028d691f34ff
Create Date: 2025-11-13 22:09:23.800524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07d9131fee5d'
down_revision = '028d691f34ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index('idx_friendship_unique', ['requester_id', 'receiver_id'], unique=True)
        batch_op.create_index('idx_friendship_users', ['requester_id', 'receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendship_status'))
        batch_op.drop_index(batch_op.f('ix_friendship_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendship_receiver_id'))
        batch_op.drop_index('idx_friendship_users')
        batch_op.drop_index('idx_friendship_unique')

    op.drop_table('friendship')
    # ### end Alembic commands ###
