"""add_avatar_and_description_to_company

Revision ID: 124cfa442472
Revises: 5161ee07b851
Create Date: 2025-11-09 15:54:14.996868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124cfa442472'
down_revision = '5161ee07b851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add avatar and description fields to company table
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove avatar and description fields from company table
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
