"""add_government_election_system

Revision ID: 13b39de23901
Revises: b9d45298824e
Create Date: 2025-11-15 20:28:34.256038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b39de23901'
down_revision = 'b9d45298824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.Enum('PRESIDENTIAL', 'CONGRESSIONAL', name='electiontype'), nullable=False),
    sa.Column('status', sa.Enum('NOMINATIONS', 'APPLICATIONS', 'VOTING', 'COMPLETED', 'CANCELLED', name='electionstatus'), nullable=False),
    sa.Column('nominations_start', sa.DateTime(), nullable=False),
    sa.Column('nominations_end', sa.DateTime(), nullable=False),
    sa.Column('voting_start', sa.DateTime(), nullable=False),
    sa.Column('voting_end', sa.DateTime(), nullable=False),
    sa.Column('term_start', sa.DateTime(), nullable=False),
    sa.Column('term_end', sa.DateTime(), nullable=False),
    sa.Column('results_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_elections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_elections_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_elections_election_type'), ['election_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_elections_status'), ['status'], unique=False)

    op.create_table('congress_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('term_start', sa.DateTime(), nullable=False),
    sa.Column('term_end', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('votes_received', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.Column('left_seat_early', sa.Boolean(), nullable=True),
    sa.Column('left_seat_at', sa.DateTime(), nullable=True),
    sa.Column('left_seat_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['government_elections.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['political_party.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.create_index('idx_country_current_congress', ['country_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_members_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_members_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_members_user_id'), ['user_id'], unique=False)

    op.create_table('country_presidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('term_start', sa.DateTime(), nullable=False),
    sa.Column('term_end', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('became_president_via', sa.String(length=20), nullable=False),
    sa.Column('left_office_early', sa.Boolean(), nullable=True),
    sa.Column('left_office_at', sa.DateTime(), nullable=True),
    sa.Column('left_office_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['government_elections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country_presidents', schema=None) as batch_op:
        batch_op.create_index('idx_country_current_president', ['country_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_presidents_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_presidents_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_presidents_user_id'), ['user_id'], unique=False)

    op.create_table('election_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='candidatestatus'), nullable=False),
    sa.Column('nominated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('votes_received', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('won_seat', sa.Boolean(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['government_elections.id'], ),
    sa.ForeignKeyConstraint(['nominated_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['political_party.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'user_id', name='uq_election_user')
    )
    with op.batch_alter_table('election_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_candidates_election_id'), ['election_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_candidates_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_candidates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_candidates_user_id'), ['user_id'], unique=False)

    op.create_table('election_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voter_user_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['election_candidates.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['government_elections.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'voter_user_id', name='uq_election_voter')
    )
    with op.batch_alter_table('election_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_votes_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_votes_election_id'), ['election_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_votes_voter_user_id'), ['voter_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_votes_voter_user_id'))
        batch_op.drop_index(batch_op.f('ix_election_votes_election_id'))
        batch_op.drop_index(batch_op.f('ix_election_votes_candidate_id'))

    op.drop_table('election_votes')
    with op.batch_alter_table('election_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_candidates_user_id'))
        batch_op.drop_index(batch_op.f('ix_election_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_election_candidates_party_id'))
        batch_op.drop_index(batch_op.f('ix_election_candidates_election_id'))

    op.drop_table('election_candidates')
    with op.batch_alter_table('country_presidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_presidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_country_presidents_is_current'))
        batch_op.drop_index(batch_op.f('ix_country_presidents_country_id'))
        batch_op.drop_index('idx_country_current_president')

    op.drop_table('country_presidents')
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_congress_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_congress_members_is_current'))
        batch_op.drop_index(batch_op.f('ix_congress_members_country_id'))
        batch_op.drop_index('idx_country_current_congress')

    op.drop_table('congress_members')
    with op.batch_alter_table('government_elections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_elections_status'))
        batch_op.drop_index(batch_op.f('ix_government_elections_election_type'))
        batch_op.drop_index(batch_op.f('ix_government_elections_country_id'))

    op.drop_table('government_elections')
    # ### end Alembic commands ###
