"""change_wages_to_currency

Revision ID: 15da41f579e6
Revises: 3de0dc4bb2b5
Create Date: 2025-11-07 12:59:16.183980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15da41f579e6'
down_revision = '3de0dc4bb2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_wage_currency', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.drop_column('daily_wage_gold')

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_wage_currency', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.drop_column('daily_wage_gold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_wage_gold', mysql.DECIMAL(precision=10, scale=4), nullable=False))
        batch_op.drop_column('daily_wage_currency')

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_wage_gold', mysql.DECIMAL(precision=10, scale=4), nullable=False))
        batch_op.drop_column('daily_wage_currency')

    # ### end Alembic commands ###
