"""implement_multi_currency_and_numeric_types

Revision ID: 1cabea73e442
Revises: 0204e2462318
Create Date: 2025-11-05 19:52:48.231813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '1cabea73e442'
down_revision = '0204e2462318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_type', sa.String(length=10), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transaction_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transaction_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transaction_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('user_currency',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='currency_amount_non_negative'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'country_id')
    )
    with op.batch_alter_table('user_currency', schema=None) as batch_op:
        batch_op.create_index('idx_user_currencies', ['user_id'], unique=False)

    # Step 1: Add timestamps with server defaults first (can be NULL initially)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Step 2: Set default values for existing rows
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE user
        SET created_at = COALESCE(birthday, NOW()),
            updated_at = NOW()
        WHERE created_at IS NULL
    """))

    # Step 3: Make timestamps NOT NULL and convert gold to Numeric
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('gold',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               nullable=False,
               server_default='0.0')
        batch_op.create_index('idx_last_studied', ['last_studied'], unique=False)
        batch_op.create_index('idx_last_trained', ['last_trained'], unique=False)

    # Step 4: Migrate existing local_currency data to user_currency table
    # For each user with citizenship and local_currency > 0, create UserCurrency record
    connection.execute(sa.text("""
        INSERT INTO user_currency (user_id, country_id, amount, created_at, updated_at)
        SELECT u.id, u.citizenship_id, u.local_currency, NOW(), NOW()
        FROM user u
        WHERE u.citizenship_id IS NOT NULL
        AND u.local_currency > 0
    """))

    # Step 5: Now safe to drop local_currency column
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('local_currency')

    # Step 6: Add CHECK constraints to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_check_constraint('gold_non_negative', 'gold >= 0')
        batch_op.create_check_constraint('wellness_range', 'wellness >= 0 AND wellness <= 100')
        batch_op.create_check_constraint('experience_non_negative', 'experience >= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add back local_currency column
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_currency', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False))

    # Step 2: Migrate data back from user_currency (only citizenship currency)
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE user u
        INNER JOIN user_currency uc ON u.id = uc.user_id AND u.citizenship_id = uc.country_id
        SET u.local_currency = uc.amount
    """))

    # Step 3: Drop CHECK constraints
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('experience_non_negative', type_='check')
        batch_op.drop_constraint('wellness_range', type_='check')
        batch_op.drop_constraint('gold_non_negative', type_='check')

    # Step 4: Drop indexes and revert columns
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_last_trained')
        batch_op.drop_index('idx_last_studied')
        batch_op.alter_column('gold',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # Step 5: Drop user_currency table
    with op.batch_alter_table('user_currency', schema=None) as batch_op:
        batch_op.drop_index('idx_user_currencies')

    op.drop_table('user_currency')

    # Step 6: Drop financial_transaction table
    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_financial_transaction_timestamp'))
        batch_op.drop_index(batch_op.f('ix_financial_transaction_country_id'))

    op.drop_table('financial_transaction')
    # ### end Alembic commands ###
