"""Add military unit models

Revision ID: 23ba6bf69281
Revises: add_new_law_types
Create Date: 2025-12-01 19:41:17.989566

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '23ba6bf69281'
down_revision = 'add_new_law_types'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=False),
    sa.Column('treasury', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_damage', sa.BigInteger(), nullable=False),
    sa.Column('battles_participated', sa.Integer(), nullable=False),
    sa.Column('battles_won', sa.Integer(), nullable=False),
    sa.Column('contracts_completed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disbanded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('treasury >= 0', name='treasury_non_negative'),
    sa.ForeignKeyConstraint(['commander_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('military_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_units_commander_id'), ['commander_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_units_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_units_is_active'), ['is_active'], unique=False)

    op.create_table('military_unit_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'achievement_type', name='unique_unit_achievement')
    )
    with op.batch_alter_table('military_unit_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_unit_achievements_unit_id'), ['unit_id'], unique=False)

    op.create_table('military_unit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_unit_applications', schema=None) as batch_op:
        batch_op.create_index('idx_pending_unit_application', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_applications_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_applications_user_id'), ['user_id'], unique=False)

    op.create_table('military_unit_inventory',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='unit_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'resource_id', 'quality')
    )
    op.create_table('military_unit_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Enum('COMMANDER', 'OFFICER', 'SOLDIER', 'RECRUIT', name='militaryunitrank'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('damage_dealt', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('left_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_unit_members', schema=None) as batch_op:
        batch_op.create_index('idx_active_unit_membership', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_members_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_members_user_id'), ['user_id'], unique=False)

    op.create_table('military_unit_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_unit_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_unit_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_messages_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_messages_user_id'), ['user_id'], unique=False)

    op.create_table('military_unit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('currency_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency_balance_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_quality', sa.Integer(), nullable=True),
    sa.Column('resource_quantity', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_unit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_unit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_transactions_unit_id'), ['unit_id'], unique=False)

    op.create_table('bounty_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('fight_for_attacker', sa.Boolean(), nullable=False),
    sa.Column('damage_required', sa.BigInteger(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('damage_required > 0', name='damage_required_positive'),
    sa.CheckConstraint('payment_amount > 0', name='payment_amount_positive'),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bounty_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounty_contracts_battle_id'), ['battle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bounty_contracts_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bounty_contracts_is_active'), ['is_active'], unique=False)

    op.create_table('bounty_contract_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'FAILED', 'CANCELLED', name='bountycontractstatus'), nullable=False),
    sa.Column('applied_by_id', sa.Integer(), nullable=False),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('damage_dealt', sa.BigInteger(), nullable=False),
    sa.Column('payment_received', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('review_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('review_rating IS NULL OR (review_rating >= 1 AND review_rating <= 5)', name='review_rating_range'),
    sa.ForeignKeyConstraint(['applied_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['bounty_contracts.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['military_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'unit_id', name='unique_contract_unit_application')
    )
    with op.batch_alter_table('bounty_contract_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounty_contract_applications_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bounty_contract_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bounty_contract_applications_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounty_contract_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounty_contract_applications_unit_id'))
        batch_op.drop_index(batch_op.f('ix_bounty_contract_applications_status'))
        batch_op.drop_index(batch_op.f('ix_bounty_contract_applications_contract_id'))

    op.drop_table('bounty_contract_applications')
    with op.batch_alter_table('bounty_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounty_contracts_is_active'))
        batch_op.drop_index(batch_op.f('ix_bounty_contracts_country_id'))
        batch_op.drop_index(batch_op.f('ix_bounty_contracts_battle_id'))

    op.drop_table('bounty_contracts')
    with op.batch_alter_table('military_unit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_transactions_unit_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_transactions_created_at'))

    op.drop_table('military_unit_transactions')
    with op.batch_alter_table('military_unit_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_messages_unit_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_messages_created_at'))

    op.drop_table('military_unit_messages')
    with op.batch_alter_table('military_unit_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_members_unit_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_members_is_active'))
        batch_op.drop_index('idx_active_unit_membership')

    op.drop_table('military_unit_members')
    op.drop_table('military_unit_inventory')
    with op.batch_alter_table('military_unit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_applications_unit_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_applications_status'))
        batch_op.drop_index('idx_pending_unit_application')

    op.drop_table('military_unit_applications')
    with op.batch_alter_table('military_unit_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_achievements_unit_id'))

    op.drop_table('military_unit_achievements')
    with op.batch_alter_table('military_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_units_is_active'))
        batch_op.drop_index(batch_op.f('ix_military_units_country_id'))
        batch_op.drop_index(batch_op.f('ix_military_units_commander_id'))

    op.drop_table('military_units')
    # ### end Alembic commands ###
