"""Add Resource market params and CountryMarketItem model

Revision ID: 254ae07de84f
Revises: 7fb7e59a057f
Create Date: 2025-05-04 10:40:32.386349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql # Import mysql dialect if needed for downgrade types


# revision identifiers, used by Alembic.
revision = '254ae07de84f'
down_revision = '7fb7e59a057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for altering table
    with op.batch_alter_table('resource', schema=None) as batch_op:
        # Add defaults directly in add_column if possible, or use server_default
        batch_op.add_column(sa.Column('market_volume_threshold', sa.Integer(), nullable=False, server_default='200'))
        batch_op.add_column(sa.Column('market_price_adjustment', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.1'))

    # Update existing rows if server_default didn't apply
    op.execute("UPDATE resource SET market_volume_threshold = 200 WHERE market_volume_threshold IS NULL")
    op.execute("UPDATE resource SET market_price_adjustment = 0.1 WHERE market_price_adjustment IS NULL")


    op.create_table('country_market_item',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    # These columns are replaced in a later migration, but were part of this step
    sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume_since_last_change', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('country_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_market_item')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('market_price_adjustment')
        batch_op.drop_column('market_volume_threshold')

    # ### end Alembic commands ###