"""add_political_party_system

Revision ID: 2ce282c8ab9f
Revises: a5565b23c0a5
Create Date: 2025-11-06 12:27:34.181429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce282c8ab9f'
down_revision = 'a5565b23c0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('political_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(length=500), nullable=True),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('president_id', sa.Integer(), nullable=False),
    sa.Column('founded_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('char_length(description) <= 500', name='party_description_length'),
    sa.CheckConstraint('char_length(name) >= 3', name='party_name_length'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['president_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'slug', name='uq_party_country_slug')
    )
    with op.batch_alter_table('political_party', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_political_party_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_president_id'), ['president_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_slug'), ['slug'], unique=False)

    op.create_table('party_election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='electionstatus'), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['political_party.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party_election', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_election_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_election_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_election_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_election_status'), ['status'], unique=False)

    op.create_table('party_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['political_party.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'party_id')
    )
    op.create_table('party_candidate',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['party_election.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('election_id', 'user_id')
    )
    op.create_table('party_vote',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['party_election.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('election_id', 'voter_id')
    )
    with op.batch_alter_table('party_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_vote_candidate_id'), ['candidate_id'], unique=False)

    # Add party_id to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_party_id'), ['party_id'], unique=False)
        batch_op.create_foreign_key(None, 'political_party', ['party_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove party_id from user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_party_id'))
        batch_op.drop_column('party_id')

    # Drop party tables
    with op.batch_alter_table('party_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_vote_candidate_id'))

    op.drop_table('party_vote')
    op.drop_table('party_candidate')
    op.drop_table('party_membership')

    with op.batch_alter_table('party_election', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_election_status'))
        batch_op.drop_index(batch_op.f('ix_party_election_start_time'))
        batch_op.drop_index(batch_op.f('ix_party_election_party_id'))
        batch_op.drop_index(batch_op.f('ix_party_election_end_time'))

    op.drop_table('party_election')

    with op.batch_alter_table('political_party', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_political_party_slug'))
        batch_op.drop_index(batch_op.f('ix_political_party_president_id'))
        batch_op.drop_index(batch_op.f('ix_political_party_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_political_party_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_political_party_country_id'))

    op.drop_table('political_party')
    # ### end Alembic commands ###
