"""add_referral_system

Revision ID: 33662fefc6c8
Revises: 2ce282c8ab9f
Create Date: 2025-11-06 13:38:44.508992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33662fefc6c8'
down_revision = '2ce282c8ab9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create referral table
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='referralstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('gold_awarded', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_index('idx_referral_referee', ['referee_id'], unique=False)
        batch_op.create_index('idx_referral_referrer_status', ['referrer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_referee_id'), ['referee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_status'), ['status'], unique=False)

    # Add referral_code to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove referral_code from user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_column('referral_code')

    # Drop referral table and indexes
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_status'))
        batch_op.drop_index(batch_op.f('ix_referral_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referral_referee_id'))
        batch_op.drop_index('idx_referral_referrer_status')
        batch_op.drop_index('idx_referral_referee')

    op.drop_table('referral')
    # ### end Alembic commands ###
