"""add_currency_price_history_table

Revision ID: 3549d5dd8b81
Revises: 5010ec7b27ad
Create Date: 2025-11-17 13:35:06.561305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3549d5dd8b81'
down_revision = '5010ec7b27ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'recorded_date', name='unique_daily_currency_rate')
    )
    with op.batch_alter_table('currency_price_history', schema=None) as batch_op:
        batch_op.create_index('idx_currency_history_lookup', ['country_id', 'recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_price_history_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_price_history_recorded_date'), ['recorded_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_price_history_recorded_date'))
        batch_op.drop_index(batch_op.f('ix_currency_price_history_country_id'))
        batch_op.drop_index('idx_currency_history_lookup')

    op.drop_table('currency_price_history')
    # ### end Alembic commands ###
