"""add_company_system

Revision ID: 3de0dc4bb2b5
Revises: 951868b91caf
Create Date: 2025-11-07 12:29:34.406693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de0dc4bb2b5'
down_revision = '951868b91caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_type', sa.Enum('MINING', 'RESOURCE_EXTRACTION', 'FARMING', 'WEAPON_MANUFACTURING', 'CONSUMER_GOODS', 'SEMI_PRODUCT', 'CONSTRUCTION', name='companytype'), nullable=False),
    sa.Column('quality_level', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('gold_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_production_resource_id', sa.Integer(), nullable=True),
    sa.Column('production_progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('currency_balance >= 0', name='check_currency_balance_positive'),
    sa.CheckConstraint('gold_balance >= 0', name='check_gold_balance_positive'),
    sa.CheckConstraint('quality_level >= 1 AND quality_level <= 5', name='check_quality_level'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['current_production_resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_company_type'), ['company_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_owner_id'), ['owner_id'], unique=False)

    op.create_table('company_inventory',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quality IS NULL OR (quality >= 1 AND quality <= 5)', name='check_quality_range'),
    sa.CheckConstraint('quantity >= 0', name='check_company_inventory_quantity_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'resource_id')
    )
    op.create_table('company_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('OWNER_DEPOSIT_GOLD', 'OWNER_DEPOSIT_CURRENCY', 'PRODUCT_SALE', 'CURRENCY_EXCHANGE', 'OWNER_WITHDRAWAL_GOLD', 'OWNER_WITHDRAWAL_CURRENCY', 'WAGE_PAYMENT', 'RESOURCE_PURCHASE', 'UPGRADE', 'EXPORT_LICENSE', 'RELOCATION', 'CURRENCY_EXCHANGE_SELL', name='companytransactiontype'), nullable=False),
    sa.Column('amount_gold', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_currency', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('balance_gold_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance_currency_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_transaction_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_transaction_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_wage_gold', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('last_worked', sa.Date(), nullable=True),
    sa.Column('has_worked_today', sa.Boolean(), nullable=False),
    sa.Column('total_days_worked', sa.Integer(), nullable=False),
    sa.Column('hired_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('daily_wage_gold > 0', name='check_employment_wage_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='unique_company_user_employment')
    )
    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employment_user_id'), ['user_id'], unique=False)

    op.create_table('export_license',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'country_id')
    )
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('daily_wage_gold', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('minimum_skill_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('daily_wage_gold > 0', name='check_wage_positive'),
    sa.CheckConstraint('minimum_skill_level >= 0', name='check_min_skill_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_offer_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_offer_is_active'), ['is_active'], unique=False)

    # Add can_have_quality column to resource table
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_have_quality', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove can_have_quality column from resource table
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('can_have_quality')

    # Drop company-related tables
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_offer_is_active'))
        batch_op.drop_index(batch_op.f('ix_job_offer_company_id'))

    op.drop_table('job_offer')
    op.drop_table('export_license')

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_user_id'))
        batch_op.drop_index(batch_op.f('ix_employment_company_id'))

    op.drop_table('employment')

    with op.batch_alter_table('company_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_company_transaction_created_at'))
        batch_op.drop_index(batch_op.f('ix_company_transaction_company_id'))

    op.drop_table('company_transaction')
    op.drop_table('company_inventory')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_owner_id'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_company_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_company_country_id'))
        batch_op.drop_index(batch_op.f('ix_company_company_type'))

    op.drop_table('company')
    # ### end Alembic commands ###
