"""add_market_price_history_table

Revision ID: 5010ec7b27ad
Revises: 13b39de23901
Create Date: 2025-11-17 13:21:51.886786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5010ec7b27ad'
down_revision = '13b39de23901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id', 'resource_id', 'quality'], ['country_market_item.country_id', 'country_market_item.resource_id', 'country_market_item.quality'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'resource_id', 'quality', 'recorded_date', name='unique_daily_price')
    )
    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_lookup', ['country_id', 'resource_id', 'quality', 'recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_price_history_recorded_date'), ['recorded_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_price_history_recorded_date'))
        batch_op.drop_index('idx_price_history_lookup')

    op.drop_table('market_price_history')
    # ### end Alembic commands ###
