"""Implement Web3 authentication fields for User model

Revision ID: 504b2064a3fb
Revises: aa7d35880389
Create Date: 2025-04-28 22:28:09.850983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504b2064a3fb'
down_revision = 'aa7d35880389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True) # Make email nullable as it's not required for web3 auth
        batch_op.drop_index('ix_user_login')
        batch_op.create_index(batch_op.f('ix_user_wallet_address'), ['wallet_address'], unique=True)
        batch_op.drop_column('login')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('login', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_wallet_address'))
        batch_op.create_index('ix_user_login', ['login'], unique=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False) # Make email non-nullable again if downgrading
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###