"""make_employment_id_nullable_in_work_session

Revision ID: 5161ee07b851
Revises: c2a7a3212549
Create Date: 2025-11-09 00:59:30.221666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5161ee07b851'
down_revision = 'c2a7a3212549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.alter_column('employment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.alter_column('employment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
