"""Add GoldMarket model

Revision ID: 51bb8e6f5a6d
Revises: dac8363e212c
Create Date: 2025-05-08 15:26:49.078015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb8e6f5a6d'
down_revision = 'dac8363e212c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_market',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('initial_exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('price_level', sa.Integer(), nullable=False),
    sa.Column('progress_within_level', sa.Integer(), nullable=False),
    sa.Column('volume_per_level', sa.Integer(), nullable=False),
    sa.Column('price_adjustment_per_level', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    with op.batch_alter_table('gold_market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_market_price_level'), ['price_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gold_market', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gold_market_price_level'))

    op.drop_table('gold_market')
    # ### end Alembic commands ###
