"""add_achievement_system

Revision ID: 5a2b0651248d
Revises: 07d9131fee5d
Create Date: 2025-11-15 16:47:48.695738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2b0651248d'
down_revision = '07d9131fee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('gold_reward', sa.Integer(), nullable=False),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievement_code'), ['code'], unique=True)

    op.create_table('achievement_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_code', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_code', name='unique_user_progress')
    )
    with op.batch_alter_table('achievement_progress', schema=None) as batch_op:
        batch_op.create_index('idx_user_progress', ['user_id', 'achievement_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievement_progress_achievement_code'), ['achievement_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievement_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('gold_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='unique_user_achievement')
    )
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index('idx_user_achievements', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievement_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievement_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievement_achievement_id'))
        batch_op.drop_index('idx_user_achievements')

    op.drop_table('user_achievement')

    with op.batch_alter_table('achievement_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_achievement_progress_achievement_code'))
        batch_op.drop_index('idx_user_progress')

    op.drop_table('achievement_progress')

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_code'))
        batch_op.drop_index(batch_op.f('ix_achievement_category'))

    op.drop_table('achievement')
    # ### end Alembic commands ###
