"""add_ohlc_price_columns

Revision ID: 5fb7d5f29f83
Revises: 3549d5dd8b81
Create Date: 2025-11-17 13:45:32.312186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb7d5f29f83'
down_revision = '3549d5dd8b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_production_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_production_progress_company_resource'))

    with op.batch_alter_table('currency_price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_open', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('rate_high', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('rate_low', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('rate_close', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.alter_column('exchange_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=True)

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transaction_country_timestamp'))
        batch_op.drop_index(batch_op.f('idx_transaction_currency_type'))
        batch_op.drop_index(batch_op.f('idx_transaction_type_timestamp'))
        batch_op.drop_index(batch_op.f('idx_transaction_user_timestamp'))

    with op.batch_alter_table('gold_market', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_gold_market_created_at'))
        batch_op.drop_index(batch_op.f('idx_gold_market_updated_at'))

    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_open', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('price_high', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('price_low', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('price_close', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_region_created_at'))
        batch_op.drop_index(batch_op.f('idx_region_original_owner'))
        batch_op.drop_index(batch_op.f('idx_region_updated_at'))

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_resource_created_at'))
        batch_op.drop_index(batch_op.f('idx_resource_updated_at'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_citizenship_created'))
        batch_op.drop_index(batch_op.f('idx_user_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_region_updated'))
        batch_op.drop_index(batch_op.f('idx_user_updated_at'))

    with op.batch_alter_table('user_currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_currency_country_user'))
        batch_op.drop_index(batch_op.f('idx_user_currency_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_currency_updated_at'))

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_login_at'), ['login_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_login_at'))

    with op.batch_alter_table('user_currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_currency_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_currency_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_currency_country_user'), ['country_id', 'user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_region_updated'), ['current_region_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_citizenship_created'), ['citizenship_id', 'created_at'], unique=False)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_resource_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_resource_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_region_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_region_original_owner'), ['original_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_region_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=False)
        batch_op.drop_column('price_close')
        batch_op.drop_column('price_low')
        batch_op.drop_column('price_high')
        batch_op.drop_column('price_open')

    with op.batch_alter_table('gold_market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gold_market_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_gold_market_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transaction_user_timestamp'), ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_type_timestamp'), ['transaction_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_currency_type'), ['currency_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_country_timestamp'), ['country_id', 'timestamp'], unique=False)

    with op.batch_alter_table('currency_price_history', schema=None) as batch_op:
        batch_op.alter_column('exchange_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=False)
        batch_op.drop_column('rate_close')
        batch_op.drop_column('rate_low')
        batch_op.drop_column('rate_high')
        batch_op.drop_column('rate_open')

    with op.batch_alter_table('company_production_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_production_progress_company_resource'), ['company_id', 'resource_id'], unique=True)

    # ### end Alembic commands ###
