"""add_last_worked_date_to_user

Revision ID: 79ab7f34d521
Revises: 39cdaa708f77
Create Date: 2025-11-07 18:05:01.417729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ab7f34d521'
down_revision = '39cdaa708f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_worked_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_worked_date')
    # ### end Alembic commands ###
