"""Add Resource and InventoryItem models

Revision ID: 7fb7e59a057f
Revises: fde3b3d81694
Create Date: 2025-05-04 00:49:56.138790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb7e59a057f'
down_revision = 'fde3b3d81694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('RAW_MATERIAL', 'MANUFACTURED_GOOD', 'FOOD', 'WEAPON', 'CONSTRUCTION', 'ENERGY', name='resourcecategory'), nullable=False),
    sa.Column('icon_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug') # Add unique constraint
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_slug'), ['slug'], unique=True) # Make index unique

    op.create_table('inventory_item',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False, server_default='0.0'), # Add default
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_item')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_slug'))
        batch_op.drop_index(batch_op.f('ix_resource_category'))

    op.drop_table('resource')
    # Drop the enum type if necessary (depends on backend, often handled automatically)
    # op.execute("DROP TYPE resourcecategory;")
    # ### end Alembic commands ###