"""Add current_region_id to User

Revision ID: 85a8789997a7
Revises: d2468c12bf9f
Create Date: 2025-05-03 10:19:15.201431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a8789997a7'
down_revision = 'd2468c12bf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_region_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_current_region_id'), ['current_region_id'], unique=False)
        # Ensure constraint name is unique or let Alembic handle it
        batch_op.create_foreign_key(batch_op.f('fk_user_current_region_id_region'), 'region', ['current_region_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_current_region_id_region'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_current_region_id'))
        batch_op.drop_column('current_region_id')

    # ### end Alembic commands ###