"""Add Country and Region models with relationships

Revision ID: 8cb5ea8426c7
Revises: bcfcfd861a69
Create Date: 2025-05-03 09:22:03.294326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb5ea8426c7'
down_revision = 'bcfcfd861a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('flag_code', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug') # Added unique constraint for slug
    )
    # Use batch mode for index creation
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_slug'), ['slug'], unique=True) # Unique index

    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('original_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_owner_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug') # Added unique constraint for slug
    )
    # Use batch mode for index creation
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_slug'), ['slug'], unique=True) # Unique index

    op.create_table('country_regions',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('country_id', 'region_id')
    )
    # Use batch mode for foreign key creation
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Ensure the constraint name is unique if needed, or let Alembic name it
        batch_op.create_foreign_key(batch_op.f('fk_user_citizenship_id_country'), 'country', ['citizenship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for dropping foreign key
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_citizenship_id_country'), type_='foreignkey')

    op.drop_table('country_regions')
    # Use batch mode for dropping index
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_slug'))

    op.drop_table('region')
    # Use batch mode for dropping index
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_slug'))

    op.drop_table('country')
    # ### end Alembic commands ###