"""add_messaging_system

Revision ID: 951868b91caf
Revises: 5eb53ba1361e
Create Date: 2025-11-06 23:55:11.364741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951868b91caf'
down_revision = '5eb53ba1361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('LEVEL_UP', 'HOUSE_EXPIRED', 'ELECTION_WIN', 'ADMIN_ANNOUNCEMENT', name='alerttype'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'IMPORTANT', 'URGENT', name='alertpriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('alert_data', sa.JSON(), nullable=True),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.Column('link_text', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_is_read'), ['is_read'], unique=False)

    op.create_table('blocked_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blocked_user_id', name='unique_block')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sender_deleted', sa.Boolean(), nullable=False),
    sa.Column('recipient_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('blocked_user')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_is_read'))
        batch_op.drop_index(batch_op.f('ix_alert_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_alert_type'))

    op.drop_table('alert')
    # ### end Alembic commands ###
