"""add_security_logs_table

Revision ID: 9f28f8e8232d
Revises: 5a2b0651248d
Create Date: 2025-11-15 18:30:01.822716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f28f8e8232d'
down_revision = '5a2b0651248d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'INVALID_SIGNATURE', 'INVALID_WALLET', 'SESSION_EXPIRED', 'UNAUTHORIZED_ACCESS', 'PERMISSION_DENIED', 'VALIDATION_ERROR', 'SQL_INJECTION_ATTEMPT', 'XSS_ATTEMPT', 'INVALID_INPUT', 'RATE_LIMIT_EXCEEDED', 'SUSPICIOUS_REQUEST', 'MULTIPLE_FAILED_LOGINS', 'BOT_DETECTED', 'ADMIN_ACTION', 'SENSITIVE_DATA_ACCESS', 'DATA_EXPORT', 'PASSWORD_CHANGE', 'EMAIL_CHANGE', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', name='securityeventtype'), nullable=False),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='securitylogseverity'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_wallet_address'), ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_logs_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_security_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_security_logs_resolved'))
        batch_op.drop_index(batch_op.f('ix_security_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_security_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_logs_endpoint'))
        batch_op.drop_index(batch_op.f('ix_security_logs_created_at'))

    op.drop_table('security_logs')
    # ### end Alembic commands ###
