"""Add experience field to User for leveling

Revision ID: a0fc4f8a8851
Revises: 01363b302391
Create Date: 2025-04-29 00:11:58.450603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fc4f8a8851'
down_revision = '01363b302391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the new experience column, ensuring it's not nullable and has a default
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_user_experience'), ['experience'], unique=False)

    # Update existing rows to have 0 experience if the server_default didn't apply retroactively
    # (Sometimes needed depending on DB backend and Alembic version)
    op.execute("UPDATE user SET experience = 0 WHERE experience IS NULL")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_experience'))
        batch_op.drop_column('experience')

    # ### end Alembic commands ###