"""Initial migration.

Revision ID: a8805fd0289c
Revises:
Create Date: 2025-04-28 16:01:47.266952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8805fd0289c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('salt', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('captcha', sa.SmallInteger(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('citizenship_id', sa.Integer(), nullable=True),
    sa.Column('wellness', sa.Float(), nullable=True),
    sa.Column('gold', sa.Float(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('s_manu', sa.Float(), nullable=True),
    sa.Column('s_land', sa.Float(), nullable=True),
    sa.Column('s_cons', sa.Float(), nullable=True),
    sa.Column('s_chem', sa.Float(), nullable=True),
    sa.Column('t_weapon', sa.Float(), nullable=True),
    sa.Column('t_armor', sa.Float(), nullable=True),
    sa.Column('t_mine', sa.Float(), nullable=True),
    sa.Column('t_tank', sa.Float(), nullable=True),
    sa.Column('t_heli', sa.Float(), nullable=True),
    sa.Column('t_dmg', sa.Integer(), nullable=True),
    sa.Column('t_hits', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('weapon_t', sa.SmallInteger(), nullable=True),
    sa.Column('weapon_q', sa.SmallInteger(), nullable=True),
    sa.Column('weapon_u', sa.Integer(), nullable=True),
    sa.Column('house_q', sa.SmallInteger(), nullable=True),
    sa.Column('house_u', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('co_salary', sa.Float(), nullable=True),
    sa.Column('co_leave', sa.Boolean(), nullable=True),
    sa.Column('co_hour', sa.Integer(), nullable=True),
    sa.Column('work_st', sa.Integer(), nullable=True),
    sa.Column('work_history', sa.Text(), nullable=True),
    sa.Column('h_work', sa.SmallInteger(), nullable=True),
    sa.Column('h_train', sa.SmallInteger(), nullable=True),
    sa.Column('h_learn', sa.SmallInteger(), nullable=True),
    sa.Column('wbused', sa.Integer(), nullable=True),
    sa.Column('politics', sa.SmallInteger(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('law_free', sa.SmallInteger(), nullable=True),
    sa.Column('m_worker', sa.Integer(), nullable=True),
    sa.Column('m_congress', sa.Integer(), nullable=True),
    sa.Column('m_president', sa.Integer(), nullable=True),
    sa.Column('m_media', sa.Integer(), nullable=True),
    sa.Column('m_bhero', sa.Integer(), nullable=True),
    sa.Column('m_rhero', sa.Integer(), nullable=True),
    sa.Column('m_ssolider', sa.Integer(), nullable=True),
    sa.Column('m_society', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.Boolean(), nullable=True),
    sa.Column('inventory', sa.Text(), nullable=True),
    sa.Column('newspaper_id', sa.Integer(), nullable=True),
    sa.Column('search', sa.Integer(), nullable=True),
    sa.Column('forum_reg', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Use batch mode for altering tables with SQLite compatibility in mind (good practice)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_citizenship_id'), ['citizenship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_region_id'), ['region_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_region_id'))
        batch_op.drop_index(batch_op.f('ix_user_party_id'))
        batch_op.drop_index(batch_op.f('ix_user_login'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_company_id'))
        batch_op.drop_index(batch_op.f('ix_user_citizenship_id'))

    op.drop_table('user')
    # ### end Alembic commands ###