"""add geometry fields to countries and regions

Revision ID: a8b0a55b7613
Revises: 33662fefc6c8
Create Date: 2025-11-06 17:08:03.479527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b0a55b7613'
down_revision = '33662fefc6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometry', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometry', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('geometry')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('geometry')

    # ### end Alembic commands ###
