"""Simplify User model attributes

Revision ID: aa7d35880389
Revises: ab3f624827d7
Create Date: 2025-04-28 21:19:44.840360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa7d35880389'
down_revision = 'ab3f624827d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Drop foreign key constraint first if it depends on a column being dropped
        try:
            # Attempt to drop constraint using the name from the initial migration
            batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        except Exception as e:
             # Log or print a warning if the constraint doesn't exist (might happen on reruns)
             print(f"Info: Could not drop constraint 'user_ibfk_1' (may not exist or name differs): {e}")


        # Drop indexes before dropping columns they might reference
        try: batch_op.drop_index('ix_user_company_id')
        except Exception as e: print(f"Info: Could not drop index 'ix_user_company_id': {e}")
        try: batch_op.drop_index('ix_user_party_id')
        except Exception as e: print(f"Info: Could not drop index 'ix_user_party_id': {e}")
        try: batch_op.drop_index('ix_user_region_id')
        except Exception as e: print(f"Info: Could not drop index 'ix_user_region_id': {e}")


        # Drop columns
        batch_op.drop_column('m_bhero')
        batch_op.drop_column('region_id')
        batch_op.drop_column('forum_reg')
        batch_op.drop_column('weapon_q')
        # *** THIS IS THE FIX: Ensure the original avatar column is dropped ***
        batch_op.drop_column('avatar')
        # *** END FIX ***
        batch_op.drop_column('m_rhero')
        batch_op.drop_column('t_tank')
        batch_op.drop_column('m_society')
        batch_op.drop_column('captcha')
        batch_op.drop_column('experience') # Drop old experience, new one added later
        batch_op.drop_column('wbused')
        batch_op.drop_column('law_free')
        batch_op.drop_column('party_id')
        batch_op.drop_column('m_media')
        batch_op.drop_column('inventory')
        batch_op.drop_column('t_armor')
        batch_op.drop_column('t_heli')
        batch_op.drop_column('company_id')
        batch_op.drop_column('work_st')
        batch_op.drop_column('h_work')
        batch_op.drop_column('s_cons')
        batch_op.drop_column('weapon_t')
        batch_op.drop_column('house_q')
        batch_op.drop_column('s_manu')
        batch_op.drop_column('language')
        batch_op.drop_column('t_dmg')
        batch_op.drop_column('work_history')
        batch_op.drop_column('s_land')
        batch_op.drop_column('h_learn')
        batch_op.drop_column('politics')
        batch_op.drop_column('t_hits')
        batch_op.drop_column('search')
        batch_op.drop_column('co_hour')
        batch_op.drop_column('weapon_u')
        batch_op.drop_column('t_weapon')
        batch_op.drop_column('m_worker')
        batch_op.drop_column('house_u')
        batch_op.drop_column('s_chem')
        batch_op.drop_column('co_leave')
        batch_op.drop_column('rank')
        batch_op.drop_column('m_congress')
        batch_op.drop_column('t_mine')
        batch_op.drop_column('co_salary')
        batch_op.drop_column('referrer_id') # Drop constraint first (handled above)
        batch_op.drop_column('m_president')
        batch_op.drop_column('newspaper_id')
        batch_op.drop_column('m_ssolider')
        batch_op.drop_column('h_train')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore columns in reverse order or handle dependencies
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('h_train', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m_ssolider', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('newspaper_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m_president', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referrer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_salary', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('t_mine', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('m_congress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_leave', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)) # Use TINYINT for Boolean in downgrade if needed
        batch_op.add_column(sa.Column('s_chem', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('house_u', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m_worker', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('t_weapon', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('weapon_u', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('search', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('t_hits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('politics', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('h_learn', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('s_land', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('work_history', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('t_dmg', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('s_manu', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('house_q', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weapon_t', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('s_cons', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('h_work', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('work_st', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('t_heli', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('t_armor', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('inventory', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('m_media', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('party_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('law_free', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wbused', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('captcha', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m_society', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('t_tank', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('m_rhero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        # *** Add back the original avatar column definition from the first migration ***
        batch_op.add_column(sa.Column('avatar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        # *** END FIX ***
        batch_op.add_column(sa.Column('weapon_q', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('forum_reg', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)) # Use TINYINT for Boolean
        batch_op.add_column(sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m_bhero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

        # Restore indexes
        batch_op.create_index('ix_user_region_id', ['region_id'], unique=False)
        batch_op.create_index('ix_user_party_id', ['party_id'], unique=False)
        batch_op.create_index('ix_user_company_id', ['company_id'], unique=False)
        # Restore foreign key
        # Ensure the constraint name matches what was originally created or let Alembic infer
        batch_op.create_foreign_key('user_ibfk_1', 'user', ['referrer_id'], ['id'])


    # ### end Alembic commands ###
