"""Switch market to price level system

Revision ID: b93bc293851c
Revises: 038e07badb73
Create Date: 2025-05-04 17:57:47.656915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b93bc293851c'
down_revision = '038e07badb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_market_item', schema=None) as batch_op:
        # Add new columns with defaults
        batch_op.add_column(sa.Column('price_level', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('progress_within_level', sa.Float(), nullable=False, server_default='0.0')) # Initially Float
        batch_op.create_index(batch_op.f('ix_country_market_item_price_level'), ['price_level'], unique=False)

        # Drop the old column
        batch_op.drop_column('current_stock_level')

    # Apply defaults if needed
    op.execute("UPDATE country_market_item SET price_level = 0 WHERE price_level IS NULL")
    op.execute("UPDATE country_market_item SET progress_within_level = 0.0 WHERE progress_within_level IS NULL")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_market_item', schema=None) as batch_op:
        # Add back old column
        batch_op.add_column(sa.Column('current_stock_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, server_default='0'))

        # Drop new columns/index
        batch_op.drop_index(batch_op.f('ix_country_market_item_price_level'))
        batch_op.drop_column('progress_within_level')
        batch_op.drop_column('price_level')

    # Apply default if needed
    op.execute("UPDATE country_market_item SET current_stock_level = 0 WHERE current_stock_level IS NULL")


    # ### end Alembic commands ###