"""Add work skills and last_studied to User

Revision ID: bcfcfd861a69
Revises: 016e7687122e
Create Date: 2025-04-29 18:46:29.608490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfcfd861a69'
down_revision = '016e7687122e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add columns with appropriate defaults and non-nullable constraints
        batch_op.add_column(sa.Column('skill_resource_extraction', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('skill_manufacture', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('skill_construction', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('last_studied', sa.DateTime(), nullable=True))

    # Ensure defaults are applied to existing rows if server_default didn't work
    op.execute("UPDATE user SET skill_resource_extraction = 0.0 WHERE skill_resource_extraction IS NULL")
    op.execute("UPDATE user SET skill_manufacture = 0.0 WHERE skill_manufacture IS NULL")
    op.execute("UPDATE user SET skill_construction = 0.0 WHERE skill_construction IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_studied')
        batch_op.drop_column('skill_construction')
        batch_op.drop_column('skill_manufacture')
        batch_op.drop_column('skill_resource_extraction')

    # ### end Alembic commands ###