"""add_time_allocation_and_work_session_tables

Revision ID: c2a7a3212549
Revises: dcd7c034e48f
Create Date: 2025-11-08 22:21:30.482796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2a7a3212549'
down_revision = 'dcd7c034e48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('hours_training', sa.Integer(), nullable=False),
    sa.Column('hours_studying', sa.Integer(), nullable=False),
    sa.Column('hours_working', sa.Integer(), nullable=False),
    sa.Column('training_skill', sa.String(length=50), nullable=True),
    sa.Column('studying_skill', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hours_studying >= 0 AND hours_studying <= 12', name='check_studying_hours'),
    sa.CheckConstraint('hours_training + hours_studying + hours_working <= 24', name='check_total_hours'),
    sa.CheckConstraint('hours_training >= 0 AND hours_training <= 12', name='check_training_hours'),
    sa.CheckConstraint('hours_working >= 0 AND hours_working <= 12', name='check_working_hours'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'allocation_date', name='unique_user_daily_allocation')
    )
    with op.batch_alter_table('time_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_allocation_allocation_date'), ['allocation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_allocation_user_id'), ['user_id'], unique=False)

    op.create_table('work_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Float(), nullable=False),
    sa.Column('production_points', sa.Float(), nullable=False),
    sa.Column('wage_per_pp', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('energy_spent', sa.Integer(), nullable=False),
    sa.Column('wellness_spent', sa.Integer(), nullable=False),
    sa.Column('worked_at', sa.DateTime(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_session_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_session_employment_id'), ['employment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_session_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_session_work_date'), ['work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_session_worked_at'), ['worked_at'], unique=False)

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wage_per_pp', sa.Numeric(precision=10, scale=4), nullable=False, server_default='1.0'))
        batch_op.add_column(sa.Column('total_hours_worked', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('daily_wage_currency',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=True)

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wage_per_pp', sa.Numeric(precision=10, scale=4), nullable=False, server_default='1.0'))
        batch_op.alter_column('daily_wage_currency',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=True)
        batch_op.alter_column('minimum_skill_level',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('minimum_skill_level',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('daily_wage_currency',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=False)
        batch_op.drop_column('wage_per_pp')

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.alter_column('daily_wage_currency',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=False)
        batch_op.drop_column('total_hours_worked')
        batch_op.drop_column('wage_per_pp')

    with op.batch_alter_table('work_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_session_worked_at'))
        batch_op.drop_index(batch_op.f('ix_work_session_work_date'))
        batch_op.drop_index(batch_op.f('ix_work_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_session_employment_id'))
        batch_op.drop_index(batch_op.f('ix_work_session_company_id'))

    op.drop_table('work_session')
    with op.batch_alter_table('time_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_allocation_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_allocation_allocation_date'))

    op.drop_table('time_allocation')
    # ### end Alembic commands ###
