"""Add currency fields to Country and User

Revision ID: d2468c12bf9f
Revises: 8cb5ea8426c7
Create Date: 2025-05-03 09:57:32.349919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2468c12bf9f'
down_revision = '8cb5ea8426c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add column with non-nullable constraint and default
        batch_op.add_column(sa.Column('local_currency', sa.Float(), nullable=False, server_default='0.0'))

    # Ensure default is applied to existing rows
    op.execute("UPDATE user SET local_currency = 0.0 WHERE local_currency IS NULL")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('local_currency')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('currency_code')
        batch_op.drop_column('currency_name')

    # ### end Alembic commands ###