"""add_gold_market_table

Revision ID: dac8363e212c
Revises: 023c71028da1
Create Date: 2025-05-08 15:20:04.100030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac8363e212c'
down_revision = '023c71028da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index('slug')

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index('slug')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)

    # ### end Alembic commands ###
