"""add_is_deleted_to_alert

Revision ID: dcd7c034e48f
Revises: af532e0f7717
Create Date: 2025-11-08 20:43:57.864465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd7c034e48f'
down_revision = 'af532e0f7717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_alert_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
