"""Add region neighbors relationship

Revision ID: fde3b3d81694
Revises: 85a8789997a7
Create Date: 2025-05-03 19:57:51.988331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde3b3d81694'
down_revision = '85a8789997a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_neighbors',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neighbor_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('region_id', 'neighbor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_neighbors')
    # ### end Alembic commands ###